Repository ZakariaSaafi/SkyArt, pull requests merged in 2024-07, with the labels that each got.

#42 41 services for login and signup
  SkyArt-BE/controllers/ArtistController.js
  SkyArt-BE/controllers/UserController.js
  SkyArt-BE/routes/Artist.route.js
  SkyArt-FE/src/app/AuthentificationPage/login-page/login-page.component.css
  SkyArt-FE/src/app/AuthentificationPage/login-page/login-page.component.html
  SkyArt-FE/src/app/AuthentificationPage/login-page/login-page.component.ts
  SkyArt-FE/src/app/AuthentificationPage/signup-page/signup-page.component.css
  SkyArt-FE/src/app/AuthentificationPage/signup-page/signup-page.component.html
  SkyArt-FE/src/app/AuthentificationPage/signup-page/signup-page.component.ts
  SkyArt-FE/src/app/UserProfile/user-profile/user-profile.component.html
  SkyArt-FE/src/app/UserProfile/user-profile/user-profile.component.ts
  SkyArt-FE/src/app/app.module.ts
  SkyArt-FE/src/services/User/auth.service.spec.ts
  SkyArt-FE/src/services/User/auth.service.ts
Labels: closed

#44 Implement Category Service
  SkyArt-BE/controllers/category.controller.js
  SkyArt-BE/routes/category.route.js
  SkyArt-FE/src/services/category/categories.service.spec.ts
  SkyArt-FE/src/services/category/categories.service.ts
Labels: service

#43 Implement Categories Page
  SkyArt-BE/public/uploads/image-1720123233224.png
  SkyArt-BE/public/uploads/image-1720123585866.png
  SkyArt-FE/src/app/CategoryPage/categories-search-page/categories-search-page.component.html
  SkyArt-FE/src/app/CategoryPage/categories-search-page/categories-search-page.component.ts
  SkyArt-FE/src/app/PostPage/post-detail-page/post-detail-page.component.html
  SkyArt-FE/src/app/PostPage/post-search-page/post-search-page.component.ts
  SkyArt-FE/src/app/app-routing.module.ts
  SkyArt-FE/src/app/app.module.ts
  SkyArt-FE/src/assets/css/templatemo-cyborg-gaming.css
Labels: UI

#45 Add Order Button for Post detail Page
  SkyArt-FE/src/app/CategoryPage/category-detail-page/category-detail-page.component.css
  SkyArt-FE/src/app/CategoryPage/category-detail-page/category-detail-page.component.html
  SkyArt-FE/src/app/CategoryPage/category-detail-page/category-detail-page.component.spec.ts
  SkyArt-FE/src/app/CategoryPage/category-detail-page/category-detail-page.component.ts
  SkyArt-FE/src/app/PostPage/post-detail-page/post-detail-page.component.html
  SkyArt-FE/src/app/PostPage/post-detail-page/post-detail-page.component.ts
Labels: UI

#50 "Adding all artists"
  SkyArt-BE/controllers/ArtistController.js
  SkyArt-BE/controllers/UserController.js
  SkyArt-BE/routes/Artist.route.js
  SkyArt-BE/routes/Auth.route.js
  SkyArt-FE/src/app/AuthentificationPage/login-page/login-page.component.ts
  SkyArt-FE/src/app/AuthentificationPage/signup-page/signup-page.component.ts
  SkyArt-FE/src/app/PostPage/post-search-page/post-search-page.component.html
  SkyArt-FE/src/app/PostPage/post-search-page/post-search-page.component.ts
  SkyArt-FE/src/app/UserProfile/user-profile/user-profile.component.html
  SkyArt-FE/src/app/UserProfile/user-profile/user-profile.component.ts
  SkyArt-FE/src/app/all-artist/all-artist.component.css
  SkyArt-FE/src/app/all-artist/all-artist.component.html
  SkyArt-FE/src/app/all-artist/all-artist.component.spec.ts
  SkyArt-FE/src/app/all-artist/all-artist.component.ts
  SkyArt-FE/src/app/app-routing.module.ts
  SkyArt-FE/src/app/app.module.ts
  SkyArt-FE/src/services/User/auth.service.ts
Labels: closed
