Repository ZakariaSaafi/SkyArt, pull requests merged in 2024-06, with the labels that each got.

#24 Implement Category CRUD
  SkyArt-BE/controllers/category.controller.js
  SkyArt-BE/controllers/comment.controller.js
  SkyArt-BE/controllers/post.controller.js
  SkyArt-BE/models/Category.js
  SkyArt-BE/models/Comment.js
  SkyArt-BE/models/Post.js
  SkyArt-BE/models/Rating.js
  SkyArt-BE/routes/category.route.js
  SkyArt-BE/routes/comment.route.js
  SkyArt-BE/routes/post.route.js
  SkyArt-BE/server.js
Labels: feature, prio:high

#29 Feedback + Reponse + Notification CRUD and Impl + Email Configuration
  SkyArt-BE/.env
  SkyArt-BE/config/emailConfig.js
  SkyArt-BE/controllers/feedback.controller.js
  SkyArt-BE/controllers/notification.controller.js
  SkyArt-BE/controllers/response.controller.js
  SkyArt-BE/models/Feedback.js
  SkyArt-BE/models/Notification.js
  SkyArt-BE/models/Response.js
  SkyArt-BE/routes/feedback.route.js
  SkyArt-BE/routes/notification.route.js
  SkyArt-BE/routes/response.route.js
  SkyArt-BE/server.js
Labels: resolved

#36 Implement Post Service
  SkyArt-FE/src/services/post/post.service.ts
Labels: prio:high, resolved, FE, service

#39 "Some changes on User/Artist backend"
  SkyArt-BE/controllers/ArtistController.js
  SkyArt-BE/controllers/FollowController.js
  SkyArt-BE/controllers/PasswordController.js
  SkyArt-BE/controllers/UserController.js
  SkyArt-BE/models/Artist.js
  SkyArt-BE/models/User.js
  SkyArt-BE/package.json
  SkyArt-BE/public/uploads/image-1719359441988.png
  SkyArt-BE/public/uploads/image-1719359616916.png
  SkyArt-BE/public/uploads/image-1719359656253.png
  SkyArt-BE/routes/Artist.route.js
  SkyArt-BE/routes/Auth.route.js
  SkyArt-BE/routes/Password.route.js
  SkyArt-BE/routes/follow.route.js
  SkyArt-BE/server.js
Labels: closed
